name: Run tests and publish

on:
  push:
    branches:
      # - develop
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install depencencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Run tests
        run: npm run test
#     - uses: svrooij/secret-gate-action@v1
#       id: mygate
#       with:
#         inputsToCheck: 'NPM_TOKEN'
#       env:
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#     - name: Semantic Release
#       uses: cycjimmy/semantic-release-action@v2
#       if: steps.mygate.outputs.inputsChecked == 'true'
#       id: semantic
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
